### ISSUE TITLE
Apex Legends does not allow to enable Reflex

### ISSUE THREAD

**Issue by valters-tomsons** [ishitatsuyuki/LatencyFleX#5]
Trying to enable the middleware on Apex Legends, but game doesn't seem to allow me to enable it.

What I've done, have I missed anything?
* Installed [latencyflex](https://aur.archlinux.org/packages/latencyflex-git) and [latencyflex-wine](https://aur.archlinux.org/packages/latencyflex-wine-git)
* Copied `nvapi.dll64` to `steamapps/common/Proton - Experimental/files/lib64/wine/nvapi/`
* Added `dxvk.conf` to `steamapps/common/Apex Legends/` as described in README
* Symlinked `latencyflex_layer.dll` and `latencyflex_wine.dll` from `/usr/lib/wine/x86_64-windows/` into `steamapps/compatdata/1172470/pfx/drive_c/windows/system32/`
* Added launch parameters `PROTON_ENABLE_NVAPI=1 DXVK_NVAPI_DRIVER_VERSION=49729 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 LFX=1 %command%`

[Full Log (with `DXVK_NVAPI_LOG_LEVEL=info`)](https://gist.githubusercontent.com/valters-tomsons/81f078c3459cbb8fa5d75bdd4a169f51/raw/e839aa652e388cd58e0b754839163c258a1a4def/gistfile1.txt).

System: Arch Linux 5.16.10
GPU: Radeon RX590
Driver: Mesa 21.3.6

**Comment by tizzir** [comment]
I can confirm that I have this feature working in Apex Legends.

I'm not sure if any of this helps, but here are the things that I can think of off the top of my head that might be causing the issue:

1. Make sure that the file is named `nvapi64.dll`, rather than `nvapi.dll64`. I'm sure this is just a typo, but I thought I'd mention it just in case
2. Don't forget to also copy/link over the `/usr/lib/wine/x86_64-unix/latencyflex_layer.so`, as well as the DLL files you mentioned in your report to the Proton installation. As per the README:
  > For Wine 7.x: change `/usr/lib/wine` to wherever Wine/Proton is installed. For Proton and certain distros, you also need to change `lib` to `lib64`. Copy the following files.  
  > `/usr/lib/wine/x86_64-unix/latencyflex_layer.so`
  > `/usr/lib/wine/x86_64-windows/latencyflex_layer.dll`
  > `/usr/lib/wine/x86_64-windows/latencyflex_wine.dll`

I.E. put those 3 files (2 `.dll` and 1 `.so` into their respective folders next to the `nvapi64.dll` file you've already copied over.

Hopefully this is of some help!

**Comment by ishitatsuyuki** [comment]
What tizzir said. You probably missed `lib/wine/x86_64-unix/latencyflex_layer.so`, which is often confused with the main `/usr/lib/liblatencyflex_layer.so` (both need to be present/copied). The naming is partially a consequence to make the library name common between Linux and Windows, in case native Windows support is implemented. (#3)

**Comment by poligarpi** [comment]
Recompiling nvapi64.dll did the trick for me, also not all the launch options are required, here is mine: 

gamemoderun mangohud ENABLE_VKBASALT=1 PROTON_ENABLE_NVAPI=1 LFX=1 %command%

**Comment by valters-tomsons** [comment]
Hadn't had the time to test this yet, will update :crossed_fingers:

**Comment by ishitatsuyuki** [comment]
I think you forgot to copy the DLLs into the Proton x86_64-windows directory, see the newly added troubleshooting guide https://github.com/ishitatsuyuki/LatencyFleX/blob/master/docs/TROUBLESHOOTING.md#checking-if-the-wine-bridge-is-loaded (the one in /usr/lib does not get recognized by Proton)

**Comment by valters-tomsons** [comment]
Alright, I copied the files again (without symlinking) and it seems to work fine now! Thanks!

**Comment by AsuMagic** [comment]
It did not work for me because I was embarrassingly looking at the wrong `compatdata` directory, because I had an unused one for the game in my main steam install directory for some reason, where the one actually used was on a different steam install directory. Might be worth adding to the troubleshooting guide?
